apiVersion: v1
kind: Pod
metadata:
  name: metrics-server
  labels:
    name: metrics-server
    dummy-key: dummy-value
spec:
  containers:
  - name: metrics-server
    image: vyhone/prometheus-java-simple-server:0.0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - containerPort: 1234
        name: custom-port

